app:
    resource: "@AppBundle/Controller/"
    type:     annotation

root:
    path: /admin
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /admin/map
        permanent: true

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

rest:
    resource: "@AppBundle/Controller/Rest/MapRestController.php"
    type: rest
    prefix: "api"
    defaults:
      _format: json
