# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

  appbundle.serializer.map:
      class: AppBundle\EventListener\SerializerEventSubscriber
      arguments: ['@router', '@request_stack']
      tags:
            - { name: jms_serializer.event_subscriber, class: AppBundle\Entity\Map }
