<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * IconRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class IconRepository extends EntityRepository
{
    public function search($q){
        return $this->createQueryBuilder('node')
            ->where('node.name LIKE :q OR node.title LIKE :q')
            ->setParameter('q', '%' . $q . '%')->getQuery()->getResult();
    }
}
